### ISSUE TITLE
About the real-time nature of the network

### ISSUE THREAD

**Issue by wdxpython** [lijx10/SO-Net#14]
Hello!

I read your paper and I think your work is really great!

I have a question, your input in the paper is 5000 x 3, but in reality the number of point clouds is unknown. Can this network be used to identify obstacles in real time? Can you easily reveal the real-time nature of this network?
Looking forward to your reply!

**Comment by lijx10** [comment]
Thanks for your interest.

We fix the number of input points in our paper so that we can fully utilize the computational power and memory of the GPU. In practice, the number of points may vary from time-to-time. In this case, we have a few choices:
1. Perform downsampling or upsampling of the points, so that the input to the network remain the same, and we can perform batch processing.
2. Process one point cloud in each forward computing. That is, each forward computing can take different number of input points.
3. This is the most complicated one: re-implement the network so that it takes a batch of point clouds as input, and each point cloud can have different number of points. This is possible, but requires a lot of work.

For real-time implementation:
- The deep network itself is very fast. It contains around 10 layers. For example, for a batch of 8 point clouds (each point cloud contains 1024 points), it takes around 20ms for our network to perform classification with 1080ti.
- However, training the Self-Organizing Map is time consuming. The SOM serves as an input to the deep network in our SO-Net. 
- The good news is that, the network is still performing well with Farthest Point Sampling (FPS) instead of SOM. That is, we can replace the SOM nodes with the FPS, and the performance of the network decrease a little, but still satisfying.
- To achieve best efficiency, you may consider re-implementing deep networks with TensorRT. Deep learning frameworks like PyTorch and TensorFlow trades convenience with performance. The performance of network forwarding can be improved by maybe 10 times if implemented with TensorRT.
