### ISSUE TITLE
Sampling code non-uniform?

### ISSUE THREAD

**Issue by jackd** [lijx10/SO-Net#23]
I might be mistaken, but from what I can tell the sampling code appears to be non-uniform for each triangle. Results for a single triangle shown below. See [here](http://mathworld.wolfram.com/TrianglePointPicking.html) for what I think is the issue.
![sample](https://user-images.githubusercontent.com/659115/63567006-c5821d00-c5b2-11e9-89dd-ab0529b2a3ca.jpg)

For fine-detailed meshes I doubt it will make a big difference, but for any meshes dominated by large surfaces I feel things could get hairy.

**Comment by lijx-nutonomy** [comment]
Thanks for pointing out this. I think you are right, my sampling codes are not generating uniform points. But anyway, in the end, the datasets are converted from PointNet++'s dataset, instead of sampling from meshes myself. So this won't affect the results.

But I will be more than appreciated if you could submit a pull request to fix this. Thanks again for pointing out!

**Comment by jackd** [comment]
[Done](https://github.com/lijx10/SO-Net/pull/25). If you decide to move towards preprocessing with python, I'd encourage you to check out [trimesh](https://github.com/mikedh/trimesh). It has obj loading (along with most other popular formats), surface sampling and a host of other convenient features :).

**Comment by lijx10** [comment]
Thanks! I will definitely tryout trimesh. Well, I should have used this at that time, instead of spending an hour writing a wrong mesh sampler.

**Comment by jackd** [comment]
An hour? Mate, I wrote a now abandoned [package](https://github.com/jackd/util3d) ;).
